safe_cli/safe_operator.py

safe-cli is closed unexpectedly when trying to show a safe balances/history in Kovan network.
Because it tries to show a warning message (`No tx service available for network=KOVAN`) using a variable which has a **typo**.

Fix unexpected error when showing safe balances/history in Kovan network

---

safe_cli/safe_addresses.py

Replaces `LAST_SAFE_CONTRACT` with version `1.3.0`

Use v1.3.0 contracts

---

safe_cli/operators/safe_operator.py
safe_cli/safe_addresses.py
safe_cli/safe_creator.py

- When using the safe_creator use `L2 Safe` version always unless the network is `mainnet`
- Allow L2 Safes updating (previously only not L2 Safes were supported)

Detect Safe contract addresses using configured RPC

---

README.md
safe_cli/operators/hw_accounts/exceptions.py
safe_cli/operators/hw_accounts/ledger_manager.py
safe_cli/operators/safe_operator.py
safe_cli/prompt_parser.py
safe_cli/utils.py
tests/test_ledger_manager.py
tests/test_safe_operator.py

Add derivation-path option to load ledger owners

---

safe_cli/operators/exceptions.py
safe_cli/operators/safe_operator.py
safe_cli/prompt_parser.py
tests/test_safe_operator.py

- Update master copy function was removed after 1.1.1
- Migration contracts to update from 1.3.0 to 1.4.1 are still not available
- Test update

Fix update not working for Safes > 1.1.1

---

safe_cli/operators/hw_accounts/ledger_manager.py
tests/test_ledger_manager.py

Support m derivation path

---

README.md

Closes #107 
- explains how to recreate a Safe 1.3.0 in other chain and drain the funds.

Add Safe recovery documentation

---

requirements.txt
setup.py
tests/test_ledger_manager.py

- Bump ledgereth to [0.9.1](https://github.com/mikeshultz/ledger-eth-lib/releases/tag/v0.9.1)
- Add test to ensure that LedgerAccounts are not duplicated in the the set of accounts.   
Closes #302

Fix duplicated LedgerAccounts

---

README.md

Fix error on README doc. 
Closes #316

Fix README error

---

safe_cli/operators/hw_wallets/trezor_wallet.py

Closes #322 
Always_promt is by default `False`, when is `True` enables to shows always the pin matrix when is required.

Fix pin matrix does not display

---

safe_cli/operators/hw_wallets/hw_wallet.py
safe_cli/operators/hw_wallets/hw_wallet_manager.py
safe_cli/operators/hw_wallets/ledger_wallet.py
safe_cli/operators/hw_wallets/trezor_wallet.py
safe_cli/operators/safe_operator.py
tests/test_hw_wallet_manager.py
tests/test_ledger_wallet.py
tests/test_safe_operator.py

Add support to execute transactions from ledger

---

safe_cli/operators/hw_wallets/hw_wallet_manager.py
safe_cli/operators/safe_operator.py
tests/test_hw_wallet_manager.py

Fix wrong default derivation path for Trezor

---

safe_cli/operators/hw_wallets/hw_wallet.py
safe_cli/operators/hw_wallets/ledger_wallet.py
safe_cli/operators/hw_wallets/trezor_wallet.py
safe_cli/operators/safe_operator.py
tests/test_trezor_wallet.py

Support execute transaction from Trezor

---

README.md
requirements.txt
safe_cli/operators/hw_wallets/hw_wallet_manager.py
safe_cli/operators/safe_operator.py
safe_cli/operators/safe_tx_service_operator.py
safe_cli/prompt_parser.py
safe_cli/safe_completer_constants.py
safe_cli/safe_lexer.py
setup.py
tests/test_safe_tx_service_operator.py
tests/test_trezor_wallet.py

Close #306 
- Refactor hardware wallet manager sign eip712 message.

Add support to remove not executed transactions

---

safe_cli/operators/safe_tx_service_operator.py
tests/test_safe_tx_service_operator.py

Fix missing return when proposer was not loaded between signers. 
Close #360

Fix unloaded proposer removing transaction

---

.github/workflows/ci.yml

Docker [v26](https://github.com/docker/cli/blob/v26.1.3/docs/deprecated.md) needs to create first the network before define it in network-aliases

Fix CI docker for v26

---

src/safe_cli/operators/hw_wallets/hw_wallet_manager.py
src/safe_cli/operators/safe_tx_service_operator.py

`sign_safe_tx` of `HwWalletManager`  was removing previous signatures in the `SafeTx`. 
Concatenate previous signatures and export the sorted signatures.

Fix hw_wallet overwrites previous signatures

---

src/safe_cli/operators/safe_operator.py
src/safe_cli/operators/safe_tx_service_operator.py

When the safe-cli is running on ts-service mode the threshold was wrongly updated to the new value during a `change_threshold` command call. 
The issue was that the function `prepare_and_execute_transaction` is overwritten by the `SafeTxOperator` class with the difference that instead execute the transaction in blockchain, the overwritten function POST the transaction to the Safe Transaction Service without execute it.
Update from blockchain the threshold value. 
Closes #323

Fix threshold retrieve in tx-service mode

---

tests/utils.py

Removes the variable shadowing with `i` – this variable is already being used for the outer loop.
While not being used in the inner loop, we should rename it/remove it to avoid potential issues where the variable might be referenced in the future.

Remove variable shadowing

---

pyproject.toml
requirements.txt

We are using `hexbytes` as a dependency in our `argparse_validators` however the dependency is only available transitively.
The following describes how `hexbytes` is provided:
```
hexbytes==0.3.1
├── eth-account==0.11.2 [requires: hexbytes>=0.1.0,<0.4.0]
│   └── web3==6.19.0 [requires: eth-account>=0.8.0,<0.13]
│       └── safe-eth-py==6.0.0b30 [requires: web3>=6.2.0]
│           └── safe-cli==1.2.1 [requires: safe-eth-py==6.0.0b30]
├── eth-rlp==1.0.1 [requires: hexbytes>=0.1.0,<1]
│   └── eth-account==0.11.2 [requires: eth-rlp>=0.3.0]
│       └── web3==6.19.0 [requires: eth-account>=0.8.0,<0.13]
│           └── safe-eth-py==6.0.0b30 [requires: web3>=6.2.0]
│               └── safe-cli==1.2.1 [requires: safe-eth-py==6.0.0b30]
├── trie==3.0.1 [requires: hexbytes>=0.2.3]
│   └── …
```

Explicitly declare hexbytes dependency

---

src/safe_cli/operators/hw_wallets/hw_wallet.py
src/safe_cli/operators/hw_wallets/hw_wallet_manager.py
src/safe_cli/operators/hw_wallets/ledger_wallet.py
src/safe_cli/operators/hw_wallets/trezor_wallet.py
src/safe_cli/operators/safe_operator.py
src/safe_cli/operators/safe_tx_service_operator.py
tests/test_ledger_wallet.py
tests/test_trezor_wallet.py

Add support to sign messages using hardware wallet on transaction service mode. 
Close #354 
- `sign_message` just sign with the first provided owner because Safe Transaction Service is not accepting more than one signature to create the message. https://github.com/safe-global/safe-transaction-service/blob/49c65ec7187a20e06f466ecaeccbc601e8e0f547/safe_transaction_service/safe_messages/serializers.py#L34

Add hw wallet sign message

---

src/safe_cli/tx_builder/exceptions.py
src/safe_cli/tx_builder/tx_builder_file_decoder.py
tests/test_tx_builder_file_decoder.py

Problem detected in QA validation. 
When the method we are trying to encode is not valid, we are throwing an exception. This is an error, following the [front-end tx-builder](https://github.com/safe-global/safe-react-apps/blob/8952156607a0f432555e5d699ec21eaea4f25f67/apps/tx-builder/src/utils.ts#L218) steps here should return a None.

Remove exception with invalid contract method name in tx-builder

---

README.md
src/safe_cli/safe_creator.py
tests/test_safe_creator.py

- Add new parameter `--no-confirm` to bypass `yes or no` questions
- Add new parameter `--generate-vanity-addresses` for vanity addresses
- Closes #457

Add parameter to generate vanity addresses
