safe-global/safe-cli

safe_cli.py
safe_completer.py
safe_completer_constants.py
safe_lexer.py

custom completer for the safe-cli, tab or space to trigger, arrow support included, ignore case included.

Create SafeCompleter for the CLI

---

README.md
requirements.txt
safe_cli.py
safe_cli/api/etherscan.py
safe_cli/api/gnosis_transaction.py
safe_cli/prompt_parser.py
safe_cli/safe_completer_constants.py
safe_cli/safe_operator.py
safe_cli/safe_relay_operator.py
safe_cli/safe_tx_service_operator.py
safe_cli/utils.py
safe_creator.py

- blockchain
- tx-service
- relay-service

Add new modes for the Safe-CLI

---

README.md
safe_cli/api/base_api.py
safe_cli/api/gnosis_transaction.py
safe_cli/prompt_parser.py
safe_cli/safe_completer_constants.py
safe_cli/safe_lexer.py
safe_cli/safe_operator.py

1. I didn't write this code, but I would love to see it included.

Add delegates management commands for the transaction-service

---

safe_cli/operators/safe_operator.py
safe_cli/operators/safe_tx_service_operator.py
safe_cli/prompt_parser.py
safe_cli/safe_completer_constants.py
safe_cli/utils.py
tests/test_safe_operator.py
tests/utils.py

Include new command "drain" to get Safe empty and send ether and all ERC20 tokens to a given account.
This comand works both on blockchain mode and tx-service mode.

Add command drain

---

README.md
safe_cli/api/relay_service_api.py

Rinkeby is obsolete. I used it with goerli this time and it was a bit confusing.
That's why I created this pull request.
Thank you for your wonderful software!

Modifying the sample network(Rinkeby->Goerli)

---

requirements.txt
safe_cli/version.py
setup.py

- Update safe-eth-py dependency
- Closes #198

Set version 0.5.3

---

.github/workflows/python.yml
Dockerfile
README.md

Support docker

---

safe_cli/safe_creator.py

Last web3 methods are snake_case

Rename getCode to get_code

---

.github/workflows/ci.yml

Fix coveralls

---

safe_cli/api/transaction_service_api.py

Update deprecated delegates endpoint

---

Dockerfile
safe_cli/prompt_parser.py

Also fixed Dockerfile otherwise it was complaining `When using COPY with more than one source file, the destination must be a directory and end with a / `

Fix #244, fix docker build

---

safe_cli/prompt_parser.py

Fix token-id for sending erc721 tokens

---

safe_cli/safe_completer_constants.py

Fix missing parameter in load_ledger_cli_owners helper

---

requirements.txt
safe_cli/safe_creator.py
tests/test_safe_creator.py

Predict Safe address before creating

---

safe_cli/operators/safe_tx_service_operator.py

Fix unsupported by hardware wallet

---

.github/workflows/ci.yml
setup.py

- Stop supporting Python 3.8
- Use only one Python version for linting

Support Python 3.12

---

README.md

Please don't merge until https://github.com/safe-global/safe-docs/pull/400/files is in production.

feat: move docs to docs.safe.global

---

src/safe_cli/operators/hw_wallets/hw_wallet.py

Add support for double quotation mark derivation path

---

src/safe_cli/operators/safe_operator.py
tests/test_safe_operator.py

- Related to https://github.com/safe-global/safe-eth-py/pull/1452
- Closes #471

Fix L2 migration

---

src/safe_cli/operators/safe_operator.py

Closes https://github.com/safe-global/safe-cli/issues/517

docs: add double quotes in pip install
